seed: 14

data:
  type: MultiSDFLoader
  paths: 
    - dataset/dvfdata/A_Test0
    - dataset/dvfdata/B_Test1
    - dataset/dvfdata/C_Test2
    - dataset/dvfdata/D_Test3
    - dataset/dvfdata/E_Test4
    - dataset/dvfdata/F_Test5
    - dataset/dvfdata/G_Test6
    - dataset/dvfdata/H_Test7
    - dataset/dvfdata/I_Test8
    - dataset/dvfdata/J_Test9
    - dataset/dvfdata/K_Test10
    - dataset/dvfdata/L_Test11
    - dataset/dvfdata/M_Test12
    - dataset/dvfdata/N_Test13
    - dataset/dvfdata/O_Test14
    - dataset/dvfdata/P_Test15
    - dataset/dvfdata/Q_Test16
    - dataset/dvfdata/R_Test17
    - dataset/dvfdata/S_Test18
    - dataset/dvfdata/T_Test19
    - dataset/dvfdata/U_Test20
    - dataset/dvfdata/V_Test21
    - dataset/dvfdata/W_Test22
    - dataset/dvfdata/X_Test23
    - dataset/dvfdata/Y_Test24
    - dataset/dvfdata/Z_Test25
    - dataset/dvfdata/a_Test26
    - dataset/dvfdata/b_Test27
    - dataset/dvfdata/c_Test28
    - dataset/dvfdata/d_Test29
    - dataset/dvfdata/e_Test30
    - dataset/dvfdata/f_Test31
    - dataset/dvfdata/g_Test32
    - dataset/dvfdata/h_Test33
    - dataset/dvfdata/i_Test34
    - dataset/dvfdata/j_Test35
    - dataset/dvfdata/k_Test36
    - dataset/dvfdata/l_Test37
    - dataset/dvfdata/m_Test38
    - dataset/dvfdata/n_Test39
    - dataset/dvfdata/o_Test40
    - dataset/dvfdata/p_Test41
    - dataset/dvfdata/q_Test42
    - dataset/dvfdata/r_Test43
    - dataset/dvfdata/s_Test44
    - dataset/dvfdata/t_Test45
    - dataset/dvfdata/u_Test46
    - dataset/dvfdata/v_Test47
    - dataset/dvfdata/w_Test48
    - dataset/dvfdata/x_Test49
    - dataset/dvfdata/y_Test50
    - dataset/dvfdata/z_Test51
  num_instance: 1500

training:
  gpus: [2]
  batch_size: 64
  epochs: 200
  LR: 0.0001
  weight_decay: 0.0
  lr_decay: 0.995
  save_freq: 50

log_info:
  dir_output: results
  ckpt_load: 
  ckpt_save: SDF_52_VL
  pretrained: SDF_52_VL
  epoch: 
  gif_save: ''
  png_save: ''
  
model:
  type: MultiSDF
  params:
    latent_dim: 192
    glyph_dim: 192
    hyper_hidden_layers: 4
    hyper_hidden_features: 384
    hidden_layers: 5
    hidden_features: 256

  


